"""Extract candidate host species and countries from a publication's text.

Grounded in malaviR's vocabulary (``data/gazetteer.json``, generated by
``curation/r/gazetteer.R``): a candidate "Genus species" is kept only when the
genus is a known avian host genus. This gives high precision while still catching
a *novel* species in a *known* genus (the usual case for a new lineage). Genus
abbreviations ("A. cooperii") are expanded using the full genus names seen
earlier in the same document.

Prose gives the *set* of hosts and localities a paper covers; the host x lineage x
locality matrix usually lives in a supplementary table (see ``needs_supplement``).
Associating a specific host with a specific lineage/locality is left to later
table parsing and curator review.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple

_DATA_DIR = Path(__file__).resolve().parent / "data"
_GAZETTEER_PATH = _DATA_DIR / "gazetteer.json"

# A "Genus species" candidate: capitalized genus + lowercase epithet.
_BINOMIAL = re.compile(r"\b([A-Z][a-z]{2,})\s+([a-z]{3,})\b")
# An abbreviated binomial: "A. cooperii" / "A.cooperii".
_ABBREV = re.compile(r"\b([A-Z])\.\s?([a-z]{3,})\b")

# Epithet tokens that are NOT species names: Latin/biological abbreviations,
# taxonomic words, and common English words that can follow a capitalized,
# genus-shaped token in prose ("Accipiter and ...", "Gyps species").
_EPITHET_STOPLIST = {
    # taxonomic / Latin
    "sp", "spp", "nov", "cf", "aff", "var", "subsp", "complex", "group",
    "clade", "lineage", "lineages", "sensu", "incertae", "species", "genus",
    "genera", "et", "al",
    # common English function/structure words
    "and", "the", "for", "are", "was", "were", "not", "but", "all", "any",
    "can", "may", "has", "had", "have", "will", "its", "our", "new", "two",
    "one", "both", "such", "than", "then", "when", "here", "there", "this",
    "that", "these", "those", "with", "from", "within", "between", "among",
    "also", "well", "most", "many", "some", "see", "fig", "table", "host",
    "hosts", "avian", "blood", "study", "data", "type", "like", "used",
    "using", "sample", "samples", "sequence", "sequences",
}


@dataclass
class HostGeography:
    """Candidate hosts + localities extracted from one document."""

    hosts: List[str] = field(default_factory=list)        # "Genus species"
    vectors: List[str] = field(default_factory=list)      # arthropod-vector "Genus species"
    countries: List[str] = field(default_factory=list)
    abbreviations_expanded: List[str] = field(default_factory=list)
    # Names rewritten into MalAvi's namespace ("Astur gentilis -> Accipiter
    # gentilis"), so a curator can see the paper's own wording.
    names_translated: List[str] = field(default_factory=list)
    needs_supplement: bool = False                        # paper points to a suppl. data table

    def is_empty(self) -> bool:
        return not self.hosts and not self.vectors and not self.countries


@lru_cache(maxsize=1)
def load_country_vocabulary() -> Dict[str, Set[str]]:
    """Every country name the miner can recognise, and which are new to MalAvi.

    The gazetteer's country list is derived from MalAvi's own COUNTRY_NAME
    values, so using it alone makes the miner **structurally unable to detect a
    country that MalAvi has never recorded** -- exactly the case most worth
    catching, because a first national record is notable. Observed on a 2026
    paper reporting the first haemosporidian records from The Gambia: "The
    Gambia" appears throughout the text, and the miner returned 15 other
    countries but not that one, because MalAvi holds no Gambian records.

    The vocabulary is therefore the union of
      * the countries already in MalAvi (the gazetteer), and
      * the countries on the bundled world basemap, a real geographic dataset
        (Natural Earth via world-atlas) that is already shipped for the map.

    Both halves are data, not a hand-typed list, so no country name here is
    invented and the vocabulary widens automatically if the basemap is updated.

    Returns ``{"all": ..., "in_malavi": ..., "new_to_malavi": ...}`` so a caller
    can distinguish "country we know" from "country MalAvi has never seen".
    """
    gaz = load_gazetteer()
    in_malavi = set(gaz.get("countries", []))

    basemap: Set[str] = set()
    map_path = (Path(__file__).resolve().parents[3] / "docs" / "assets" / "data"
                / "world_map.json")
    if map_path.is_file():
        with open(map_path, "r", encoding="utf-8") as fh:
            world = json.load(fh)
        basemap |= set(world.get("paths", {}))
        # Aliases map a MalAvi spelling onto a basemap name; both sides are
        # legitimate spellings to recognise in text.
        basemap |= set(world.get("aliases", {}))
        basemap |= set(world.get("aliases", {}).values())

    every = in_malavi | basemap
    return {
        "all": every,
        "in_malavi": in_malavi,
        "new_to_malavi": every - in_malavi,
    }


@lru_cache(maxsize=1)
def load_gazetteer() -> Dict[str, object]:
    """Load the cached malaviR-derived gazetteer (genera/binomials/countries)."""
    if not _GAZETTEER_PATH.is_file():
        raise FileNotFoundError(
            f"{_GAZETTEER_PATH} missing. Generate it with: "
            "Rscript curation/r/gazetteer.R > "
            "curation/src/malavi_curation/data/gazetteer.json"
        )
    with open(_GAZETTEER_PATH, "r", encoding="utf-8") as fh:
        return json.load(fh)


@lru_cache(maxsize=1)
def _known_epithets() -> frozenset:
    """Species epithets seen in the gazetteer's host + vector binomials (lowercased).

    Used to recover names whose epithet picked up a trailing superscript footnote
    letter in a table (``Diglossa albilateraa`` -> ``albilatera``).
    """
    gaz = load_gazetteer()
    binomials = list(gaz["binomials"]) + list(gaz.get("vector_binomials", []))
    return frozenset(b.split()[-1].lower() for b in binomials if len(b.split()) >= 2)


# Mentions of supplementary data that often hold the structured host table.
_SUPPL = re.compile(r"\b(suppl\w*\s+(data|table|material)|table\s+s\d|additional\s+file)\b",
                    re.IGNORECASE)

# Common country aliases -> the canonical name used in MalAvi's gazetteer.
_COUNTRY_ALIASES = {
    "USA": "United States", "U.S.A.": "United States", "U.S.": "United States",
    "United States of America": "United States", "UK": "United Kingdom",
    "U.K.": "United Kingdom", "Great Britain": "United Kingdom",
    "Czech Republic": "Czech Republic", "Republic of Korea": "South Korea",
}


def extract_hosts_geography(
    text: str,
    known_genera: Optional[Set[str]] = None,
    countries: Optional[Set[str]] = None,
    expand_abbreviations: bool = False,
    known_vector_genera: Optional[Set[str]] = None,
) -> HostGeography:
    """Extract candidate host + vector binomials and countries from ``text``.

    ``known_genera``, ``known_vector_genera`` and ``countries`` default to the
    malaviR gazetteer. Pass explicit sets to test or to use a different reference
    vocabulary. Host genera (avian) and vector genera (arthropod) are disjoint
    vocabularies, so a binomial is classified as one or the other by its genus.

    ``expand_abbreviations`` (default False) controls expansion of abbreviated
    binomials like "A. cooperii". It is off by default because a single-letter
    initial conflates host genera with parasite genera (e.g. "H." -> Haemoproteus
    vs Haliaeetus, "P." -> Plasmodium vs Parus), producing false hosts. Papers
    spell out the binomial at first mention, so full-binomial extraction already
    achieves full recall on the benchmark without this.
    """
    if known_genera is None or countries is None or known_vector_genera is None:
        gaz = load_gazetteer()
        if known_genera is None:
            # MalAvi's own genera, plus the genera it does not use but which are
            # known to map onto it. Without the second set, a paper written in
            # current taxonomy has its hosts discarded here as non-birds: "Astur
            # gentilis" (Harl et al 2026) and "Crithagra flaviventris" (Perrin et
            # al 2026) are avian hosts MalAvi files under other genus names.
            from .host_names import synonym_genera

            known_genera = set(gaz["genera"]) | set(synonym_genera())
        if countries is None:
            # Deliberately NOT gaz["countries"]: that is only what MalAvi has
            # already recorded, which cannot match a country new to the
            # database. See load_country_vocabulary().
            countries = load_country_vocabulary()["all"]
        if known_vector_genera is None:
            known_vector_genera = set(gaz.get("vector_genera", []))

    flat = re.sub(r"\s+", " ", text)

    result = HostGeography(needs_supplement=bool(_SUPPL.search(flat)))

    # Pass 1: full binomials with a known genus. A known avian genus -> host; a
    # known arthropod-vector genus -> vector. Record genus->full name so we can
    # expand abbreviations unambiguously.
    known_epithets = _known_epithets()
    hosts: Set[str] = set()
    vectors: Set[str] = set()
    initial_to_genera: Dict[str, Set[str]] = {}
    for genus, epithet in _BINOMIAL.findall(flat):
        is_host = genus in known_genera
        is_vector = genus in known_vector_genera
        if not (is_host or is_vector):
            continue
        e = epithet.lower()
        if e in _EPITHET_STOPLIST:
            continue
        # In tables a superscript footnote marker is rendered glued onto the
        # epithet ("albilateraa", "ornatusa"). If the raw epithet is unknown but
        # dropping the trailing letter yields a *known* epithet, use the corrected
        # form. Novel species in a known genus (epithet simply unseen) are kept
        # as-is — this only rewrites when the stripped form is recognized.
        if e not in known_epithets and len(e) >= 5 and e[:-1] in known_epithets:
            epithet = epithet[:-1]
        if is_host:
            hosts.add(f"{genus} {epithet}")
            initial_to_genera.setdefault(genus[0], set()).add(genus)
        else:
            vectors.add(f"{genus} {epithet}")

    # Pass 2 (opt-in): abbreviated binomials, expanded only when the initial maps
    # to a single known genus seen in this document. Off by default -- see the
    # docstring on parasite/host initial conflation.
    expanded: List[str] = []
    if expand_abbreviations:
        for initial, epithet in _ABBREV.findall(flat):
            if epithet.lower() in _EPITHET_STOPLIST:
                continue
            candidates = initial_to_genera.get(initial)
            if candidates and len(candidates) == 1:
                genus = next(iter(candidates))
                name = f"{genus} {epithet}"
                if name not in hosts:
                    hosts.add(name)
                    expanded.append(name)

    # Countries: gazetteer terms present as whole words in the text, plus common
    # aliases (e.g. "USA" -> "United States") mapped to the canonical name.
    found = {c for c in countries if re.search(r"\b" + re.escape(c) + r"\b", flat)}
    for alias, canonical in _COUNTRY_ALIASES.items():
        if canonical in countries and re.search(r"\b" + re.escape(alias) + r"\b", flat):
            found.add(canonical)

    # "The Gambia" and "The Netherlands" are how these are written in prose; the
    # bare name is what every vocabulary stores. Match the article form too, so
    # the country is not missed purely because the paper is written correctly.
    for country in list(countries):
        if country not in found and re.search(r"\bThe " + re.escape(country) + r"\b", flat):
            found.add(country)

    found_countries = sorted(found)

    # Translate names into MalAvi's namespace (Astur gentilis -> Accipiter
    # gentilis) so the candidate list a curator reads, and any join against the
    # database, both speak the database's own language. Only documented genus
    # revisions apply, and each translation is recorded rather than silent.
    result.hosts, host_translations = _canonicalize_names(hosts, "hosts")
    result.vectors, vector_translations = _canonicalize_names(vectors, "vectors")
    result.names_translated = sorted(host_translations + vector_translations)
    result.countries = found_countries
    result.abbreviations_expanded = sorted(set(expanded))
    return result


def _canonicalize_names(names: Set[str], kind: str) -> Tuple[List[str], List[str]]:
    """Map a set of binomials into MalAvi's namespace.

    Returns the deduplicated names plus a human-readable record of what changed
    ("Astur gentilis -> Accipiter gentilis"). Deduplication happens *after* the
    mapping, because two spellings in one paper can be the same bird.
    """
    from .host_names import canonical_host

    canonical: Set[str] = set()
    translations: List[str] = []
    for name in names:
        resolved = canonical_host(name, kind=kind)
        canonical.add(resolved.name)
        if resolved.changed:
            translations.append(f"{resolved.source_name} -> {resolved.name}")
    return sorted(canonical), translations
