# @title Index the pinned MalAvi release for row-level lookups
# @purpose Load the pinned release's host table once and expose the lookups the
#          row-level flags need: known lineage names, known host binomials, and
#          which references already record a given lineage x host association.
# @why A row cannot be triaged without knowing whether MalAvi already holds it.
#      "New to MalAvi" is the whole product; "MalAvi already has this under an
#      earlier paper" is a correctly-read re-observation, not an error.
# @input docs/assets/downloads/tables/hosts_and_sites_<release>.csv
# @input docs/assets/downloads/tables/grand_lineage_summary_<release>.csv
# @output in-memory index (no files written)
# @program python
# @critical-var TABLE_DIR
"""Lookups over the pinned MalAvi release, for row-level triage.

``gate.py`` already answers two questions from ``data/db_snapshot.json`` (is this
lineage name taken? is this accession already curated?). Neither of those can
answer the question a curator actually asks of a candidate row:

    is this *association* -- this lineage, in this host -- something MalAvi
    already holds, and if so, under whose paper?

That needs the release's host table, which is not in the snapshot. It is,
however, already in the repository: the pinned release ships as CSV under
``docs/assets/downloads/tables/`` because the public site serves it as a
download. So the index is built from that, directly and offline.

Why read the CSV rather than extend the snapshot: ``db_snapshot.json`` is
generated by ``curation/r/gate_reference.R`` and therefore needs R and malaviR to
regenerate. The release CSVs are the pinned release itself and are already
committed, so reading them adds no build step and cannot go stale relative to the
release the rest of the pipeline is pinned to. The parse costs about a second on
a 4 MB table, which is why every accessor here is cached for the process.

Everything is deterministic and offline. When the tables are absent (a checkout
without the site downloads) every accessor returns an empty result, and the
callers -- which only ever *add* flags -- simply raise fewer of them. Nothing
fails and nothing is dropped.
"""
from __future__ import annotations

import csv
import re
from collections import defaultdict
from functools import lru_cache
from pathlib import Path
from typing import Dict, FrozenSet, List, Optional, Set, Tuple

from .config import repo_root

# Where the pinned release's CSV exports live. This is the same directory the
# public site serves its downloads from, so the index and the published tables
# can never disagree.
_TABLE_SUBDIR = ("docs", "assets", "downloads", "tables")


def table_dir() -> Path:
    """Directory holding the pinned release's CSV exports."""
    return repo_root().joinpath(*_TABLE_SUBDIR)


# --- Normalization ---------------------------------------------------------
#
# These must agree with the benchmark's normalizers (ground_truth_check.py), or
# the pipeline and the scorer would disagree about what counts as the same
# lineage or the same host. They are deliberately written the same way.

def norm_lineage(value: Optional[str]) -> str:
    """Upper-case a lineage name and strip all whitespace."""
    return re.sub(r"\s+", "", (value or "").strip()).upper()


def norm_species(value: Optional[str]) -> str:
    """Reduce a species string to a comparable ``GENUS SPECIES`` binomial.

    MalAvi stores GENUS_NAME and SPECIES_NAME separately and SPECIES_NAME often
    repeats the genus, so a pasted value can read ``Pipile Pipile jacutinga``.
    Taking the last two whitespace tokens yields the binomial from either form.
    Subgenus parentheses and stray punctuation are stripped first.
    """
    text = re.sub(r"\([^)]*\)", " ", value or "")      # drop "(Subgenus)"
    text = re.sub(r"[^A-Za-z\s.-]", " ", text)         # drop stray punctuation
    parts = text.split()
    if len(parts) >= 2:
        return f"{parts[-2]} {parts[-1]}".upper()
    return " ".join(parts).upper()


def norm_country(value: Optional[str]) -> str:
    """Collapse whitespace and upper-case a country name."""
    return re.sub(r"\s+", " ", (value or "").strip()).upper()


# --- Loading ---------------------------------------------------------------

@lru_cache(maxsize=1)
def pinned_release() -> Optional[str]:
    """The release date stamped on the CSV exports, or None if there are none.

    The filenames carry the release (``hosts_and_sites_2026-03-23.csv``), and the
    newest one wins so a checkout holding two releases uses the later.
    """
    directory = table_dir()
    if not directory.is_dir():
        return None
    dates = sorted({
        match.group(1)
        for path in directory.glob("*.csv")
        if (match := re.search(r"_(\d{4}-\d{2}-\d{2})\.csv$", path.name))
    })
    return dates[-1] if dates else None


def _read_table(stem: str) -> List[Dict[str, str]]:
    """Read one release CSV as a list of dicts; empty when it is not there."""
    release = pinned_release()
    if release is None:
        return []
    path = table_dir() / f"{stem}_{release}.csv"
    if not path.is_file():
        return []
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


class ReleaseIndex:
    """Everything the row-level flags need to know about the pinned release.

    Built once per process via :func:`load_release_index`. An index built from a
    missing table is *empty*, not an error: an empty index means the flags that
    depend on it stay silent, which is the safe direction because every flag is
    additive and none of them gates.
    """

    def __init__(self, host_rows: List[Dict[str, str]],
                 lineage_rows: List[Dict[str, str]]) -> None:
        # (lineage, host) -> every REFERENCE_NAME MalAvi credits with it. The
        # reference names matter and not just the membership test: when a row
        # duplicates an association MalAvi already holds, the curator wants to
        # see *which* paper holds it, because that is how they tell a genuine
        # re-observation from a mis-attributed reprint.
        pair_references: Dict[Tuple[str, str], Set[str]] = defaultdict(set)
        lineages: Set[str] = set()
        hosts: Set[str] = set()
        countries: Set[str] = set()

        for row in host_rows:
            lineage = norm_lineage(row.get("LINEAGE_NAME"))
            host = norm_species(row.get("SPECIES_NAME"))
            country = norm_country(row.get("COUNTRY_NAME"))
            if lineage:
                lineages.add(lineage)
            if host:
                hosts.add(host)
            if country:
                countries.add(country)
            if lineage and host:
                reference = (row.get("REFERENCE_NAME") or "").strip()
                pair_references[(lineage, host)].add(reference)

        # The lineage summary carries names that the host table may not (a
        # lineage known only from a vector, or deposited but not yet tied to a
        # host), plus the representative accession per lineage.
        accession_to_lineage: Dict[str, str] = {}
        for row in lineage_rows:
            # The release's own spelling, kept verbatim. A few lineage names are
            # genuinely mixed-case ("REB12p"), and this value is shown to a
            # curator, who must see the name MalAvi actually files it under
            # rather than an upper-cased approximation of it. Comparisons
            # normalize both sides instead (see ``knows_lineage``).
            printed_lineage = (row.get("LINEAGE_NAME") or "").strip()
            lineage = norm_lineage(printed_lineage)
            if lineage:
                lineages.add(lineage)
            raw_accession = (row.get("GENBANK_ACC") or "").strip()
            # A cell can hold export artifacts and, rarely, several accessions;
            # keep only well-formed nucleotide accessions, matching the shape
            # test the accession miner and gate_reference.R both apply.
            for token in re.split(r"[^A-Za-z0-9.]+", raw_accession):
                accession = re.sub(r"\.\d+$", "", token.strip().upper())
                if re.fullmatch(r"[A-Z]{1,2}\d{5,6}", accession) and lineage:
                    accession_to_lineage[accession] = printed_lineage

        self.pair_references: Dict[Tuple[str, str], Set[str]] = dict(pair_references)
        self.lineages: FrozenSet[str] = frozenset(lineages)
        self.hosts: FrozenSet[str] = frozenset(hosts)
        self.countries: FrozenSet[str] = frozenset(countries)
        self.accession_to_lineage: Dict[str, str] = accession_to_lineage

    # --- queries -----------------------------------------------------------

    @property
    def is_empty(self) -> bool:
        """True when no release table was found, so no lookup is meaningful."""
        return not self.lineages and not self.hosts

    def knows_lineage(self, lineage: Optional[str]) -> bool:
        """Is this a lineage name MalAvi already holds?"""
        name = norm_lineage(lineage)
        return bool(name) and name in self.lineages

    def knows_host(self, host: Optional[str]) -> bool:
        """Is this a host binomial MalAvi already holds?

        A False here means only "MalAvi has no record of this host", which is
        emphatically **not** the same as "this host is wrong" -- Astur gentilis,
        Agelaioides badius and Casmerodius albus are real birds absent from the
        database. Callers must treat it as information, never as a rejection.
        """
        name = norm_species(host)
        return bool(name) and name in self.hosts

    def knows_country(self, country: Optional[str]) -> bool:
        """Is this a country MalAvi already holds a record from?"""
        name = norm_country(country)
        return bool(name) and name in self.countries

    def references_for_pair(self, lineage: Optional[str],
                            host: Optional[str]) -> Set[str]:
        """References MalAvi credits with this association; empty if it has none."""
        key = (norm_lineage(lineage), norm_species(host))
        if not key[0] or not key[1]:
            return set()
        return set(self.pair_references.get(key, ()))

    def lineage_for_accession(self, accession: Optional[str]) -> Optional[str]:
        """The lineage MalAvi curates this accession under, in MalAvi's spelling.

        Returned verbatim (``REB12p``, not ``REB12P``) because it is shown to a
        curator. Compare it with :func:`norm_lineage` on both sides.
        """
        if not accession:
            return None
        normalized = re.sub(r"\.\d+$", "", accession.strip().upper())
        return self.accession_to_lineage.get(normalized)


@lru_cache(maxsize=1)
def load_release_index() -> ReleaseIndex:
    """Build (once) the index over the pinned release's CSV exports."""
    return ReleaseIndex(host_rows=_read_table("hosts_and_sites"),
                        lineage_rows=_read_table("grand_lineage_summary"))
